 - name: Create a directory script nutanix
   file:
     path: "{{ dir_script }}"
     state: directory
     mode: '0744'
   tags:
     - createVmLinuxTemplateCentos
   ignore_errors: yes
   failed_when: false
   when: ansible_default_ipv4.address == "10.40.2.19"

 - name: Copy Script template
   template:
     src: createVmLinuxTemplateCentos.j2
     dest: "{{ createVmLinuxTemplateCentos_script_path }}"
     owner: root
     group: root
     mode: 0744
   tags:
     - createVmLinuxTemplateCentos
   ignore_errors: yes
   failed_when: false
   when: ansible_default_ipv4.address == "10.40.2.19"

 - name: Exec Script Create VM Template Linux Centos
   command: bash "{{ createVmLinuxTemplateCentos_script_path }}"
   tags:
     - createVmLinuxTemplateCentos
   ignore_errors: yes
   failed_when: false
   when: ansible_default_ipv4.address == "10.40.2.19"

...
